# Generated by Django 6.0.4 on 2026-05-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('meta', models.CharField(blank=True, help_text='e.g. Picar Technology · 2024', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', 'Work'), ('edu', 'Education')], default='work', max_length=10)),
                ('period', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shivani Sonker', max_length=100)),
                ('tagline', models.CharField(default='Python · Django · React · AI/LLM Integration', max_length=200)),
                ('bio_1', models.TextField(default='')),
                ('bio_2', models.TextField(default='')),
                ('bio_3', models.TextField(default='')),
                ('email', models.EmailField(default='shivanisonker991@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 8400864952', max_length=20)),
                ('location', models.CharField(default='Lucknow, Uttar Pradesh, India', max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('years_exp', models.CharField(default='3+', max_length=10)),
                ('efficiency_boost', models.CharField(default='40%', max_length=10)),
                ('banking_projects', models.CharField(default='18+', max_length=10)),
                ('data_accuracy', models.CharField(default='99%', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(help_text='Comma-separated: Python,Django,React', max_length=300)),
                ('emoji', models.CharField(default='🌐', max_length=10)),
                ('gradient_class', models.CharField(default='pt1', help_text='CSS class: pt1 pt2 pt3 pt4 pt5 pt6', max_length=10)),
                ('live_url', models.URLField(blank=True, help_text='Live demo URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub URL')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(default=80, help_text='0-100')),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_in_pills', models.BooleanField(default=True, help_text='Show in About section pills')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
